# Generated by Django 3.2 on 2021-04-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_title', models.CharField(max_length=100)),
                ('prayer_text', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('last_prayed_date', models.DateTimeField(verbose_name='date last prayed')),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
