# Generated by Django 3.2 on 2021-05-01 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date to expire'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='frequency',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='last_prayed_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date last prayed'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer_text',
            field=models.TextField(max_length=200),
        ),
    ]
