# Generated by Django 3.2 on 2021-05-01 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayer', '0002_auto_20210430_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to=settings.AUTH_USER_MODEL),
        ),
    ]
