# Generated by Django 3.2 on 2021-05-04 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayer', '0005_dailyprayerlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprayerlist',
            name='prayer',
        ),
        migrations.AddField(
            model_name='dailyprayerlist',
            name='prayer',
            field=models.ManyToManyField(to='prayer.Prayer'),
        ),
        migrations.AlterField(
            model_name='dailyprayerlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
