# Generated by Django 3.2 on 2021-05-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0006_auto_20210503_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='date to expire'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='frequency',
            field=models.IntegerField(choices=[(-1, 'Rotating'), (1, 'Daily')], default=-1),
        ),
    ]
