# Generated by Django 3.0.11 on 2021-05-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0007_auto_20210508_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprayerlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
