# Generated by Django 3.2.3 on 2021-05-30 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayer', '0009_auto_20210517_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Selective'), (2, 'Public')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='visible_to',
            field=models.ManyToManyField(related_name='others_prayers', to=settings.AUTH_USER_MODEL),
        ),
    ]
