# Generated by Django 3.2.3 on 2021-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0010_auto_20210530_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Selective'), (2, 'Public')], default=0),
        ),
    ]
