# Generated by Django 3.2.3 on 2021-06-01 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0011_alter_prayer_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='reference',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='prayer.prayer'),
        ),
    ]
