# Generated by Django 3.2.3 on 2021-06-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0012_prayer_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayer',
            old_name='reference',
            new_name='reference_prayer',
        ),
    ]
